name: Build and Deploy with Docker Compose
on:
  push:
    branches:
      - qa
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Set up node version
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: Install dependencies
        run:  npm install --legacy-peer-deps

      - name: Build project
        run: npm run build && ls

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST_QA }}
          username: ${{ secrets.FTP_USERNAME_QA }}
          password: ${{ secrets.FTP_PASSWORD_QA }}
          server-dir: ${{ vars.REMOTE_PATH_QA_FRONT_SAE }}
          local-dir: ./dist/

      - name: Deploy with Docker Compose
        run: cd ${{ vars.REMOTE_PATH_QA_COMPOSER }} && docker compose up --build -d