name: Build and Deploy with Docker Compose
on:
  push:
    branches:
      - qa
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Generar archivo .env
        uses: actions/github-script@v6.4.0
        with:
          script: |
            const fs = require('fs');
            const content = `
            SKIP_PREFLIGHT_CHECK=true\n
            REACT_APP_BASENAME=/\n
            REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}\n
            REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}\n
            FRONT_PORT=3050\n
            CHOKIDAR_USEPOLLING=true\n`;
            fs.writeFileSync('.env', content);

      - name: Set up node version
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: Install dependencies
        run:  npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST_QA }}
          username: ${{ secrets.FTP_USERNAME_QA }}
          password: ${{ secrets.FTP_PASSWORD_QA }}
          server-dir: ${{ vars.REMOTE_PATH_QA_FRONT_SAE }}
          local-dir: ./build/

      - name: Deploy with Docker Compose
        run: cd ${{ vars.REMOTE_PATH_QA_COMPOSER }} && docker compose up --build -d