name: Build and Deploy with Docker Compose
on:
  push:
    branches:
      - qa
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Set up node version
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - name: Install dependencies
        run:  npm install --legacy-peer-deps

      - name: Build project
        run: npm run build && ls

      - name: Deploy
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          TARGET: ${{ vars.REMOTE_PATH_QA_FRONT_SAE }}
          SOURCE: "build/"

      - name: Deploy with Docker Compose
        run: cd ${{ vars.REMOTE_PATH_QA_COMPOSER }} && docker compose up --build -d